# Generated by Django 2.0 on 2019-02-12 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['secuencial'],
            },
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.NullBooleanField()),
            ],
            options={
                'ordering': ['secuencial'],
            },
        ),
        migrations.CreateModel(
            name='Controlactivdad',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('proceso', models.CharField(blank=True, max_length=1, null=True)),
                ('estado', models.NullBooleanField()),
            ],
            options={
                'ordering': ['secuencial'],
            },
        ),
        migrations.CreateModel(
            name='Detalleactividad',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('numerosemana', models.IntegerField()),
                ('secuencial_actividad', models.ForeignKey(db_column='secuencial_actividad', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Actividad')),
            ],
            options={
                'ordering': ['secuencial'],
            },
        ),
        migrations.CreateModel(
            name='Detalleplanificacionactividad',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('estado', models.CharField(max_length=1)),
                ('secuencial_actividad', models.ForeignKey(db_column='secuencial_actividad', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Actividad')),
            ],
            options={
                'ordering': ['secuencial'],
            },
        ),
        migrations.CreateModel(
            name='Feriados',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=120, null=True)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('estado', models.NullBooleanField()),
            ],
            options={
                'ordering': ['secuencial'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('estado', models.NullBooleanField()),
            ],
            options={
                'ordering': ['secuencial'],
            },
        ),
        migrations.CreateModel(
            name='Listacontrol',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.NullBooleanField()),
            ],
            options={
                'ordering': ['secuencial'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.NullBooleanField()),
            ],
            options={
                'ordering': ['secuencial'],
            },
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('numerosemana', models.IntegerField(blank=True, null=True)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['secuencial'],
            },
        ),
        migrations.CreateModel(
            name='Requerido',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.NullBooleanField()),
            ],
            options={
                'ordering': ['secuencial'],
            },
        ),
        migrations.CreateModel(
            name='Tipoactividad',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['secuencial'],
            },
        ),
        migrations.CreateModel(
            name='Tipoturno',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.NullBooleanField()),
            ],
            options={
                'ordering': ['secuencial'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('secuencial_horario', models.ForeignKey(db_column='secuencial_horario', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Horario')),
                ('secuencial_tipoturno', models.ForeignKey(db_column='secuencial_tipoturno', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Tipoturno')),
            ],
            options={
                'ordering': ['secuencial'],
            },
        ),
        migrations.CreateModel(
            name='Turnoferiado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencial_feriado', models.ForeignKey(db_column='secuencial_feriado', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Feriados')),
                ('secuencial_tipoturno', models.ForeignKey(db_column='secuencial_tipoturno', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Tipoturno')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.NullBooleanField()),
                ('secuencial_persona', models.ForeignKey(blank=True, db_column='secuencial_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Persona')),
            ],
            options={
                'ordering': ['secuencial'],
            },
        ),
        migrations.AddField(
            model_name='turno',
            name='secuencial_usuario',
            field=models.ForeignKey(db_column='secuencial_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Usuario'),
        ),
        migrations.AddField(
            model_name='listacontrol',
            name='secuencial_tipocontrol',
            field=models.ForeignKey(blank=True, db_column='secuencial_tipocontrol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Tipoturno'),
        ),
        migrations.AddField(
            model_name='detalleplanificacionactividad',
            name='secuencial_planificacion',
            field=models.ForeignKey(db_column='secuencial_planificacion', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Planificacion'),
        ),
        migrations.AddField(
            model_name='detalleactividad',
            name='secuencial_tipoactividad',
            field=models.ForeignKey(db_column='secuencial_tipoactividad', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Tipoactividad'),
        ),
        migrations.AddField(
            model_name='controlactivdad',
            name='secuencial_listacontrol',
            field=models.ForeignKey(db_column='secuencial_listacontrol', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Listacontrol'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='secuencial_cobertura',
            field=models.ForeignKey(db_column='secuencial_cobertura', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Cobertura'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='secuencial_requerido',
            field=models.ForeignKey(db_column='secuencial_requerido', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Requerido'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='secuencial_usuario',
            field=models.ForeignKey(db_column='secuencial_usuario', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Usuario'),
        ),
    ]
