# Generated by Django 2.0 on 2019-02-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleactividad',
            name='fechaproceso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
