# Generated by Django 2.0 on 2019-03-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_detalleactividad_fechaproceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleplanificacionactividad',
            name='estado',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
