# Generated by Django 2.0 on 2019-03-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20190313_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notasplanificacion',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.TextField(null=True)),
                ('fechaproceso', models.DateTimeField(blank=True, null=True)),
                ('secuencial_planificacion', models.ForeignKey(db_column='secuencial_planificacion', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Planificacion')),
            ],
        ),
    ]
