# Generated by Django 2.0 on 2019-03-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_notasplanificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notasplanificacion',
            options={'ordering': ['secuencial']},
        ),
    ]
