# Generated by Django 2.0 on 2019-03-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20190313_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleplanificacionactividad',
            name='estado',
            field=models.CharField(choices=[('I', 'Iniciado'), ('E', 'Ejecutando'), ('T', 'Terminado')], default='I', max_length=1),
        ),
    ]
