# Generated by Django 2.0 on 2019-03-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20190313_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasplanificacion',
            name='fechaproceso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
