# Generated by Django 2.0 on 2019-04-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_cargo_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeTI',
            fields=[
                ('secuencial', models.AutoField(primary_key=True, serialize=False)),
                ('codigoinforme', models.CharField(max_length=4)),
                ('fecha', models.DateField()),
                ('detalle', models.TextField()),
                ('secuencial_detalleplanificacion', models.ForeignKey(db_column='secuencial_detalleplanificacion', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.Detalleplanificacionactividad')),
            ],
        ),
    ]
